import type { Metadata } from "next";
import { LandingFeaturesGrid } from "@/components/landing/landing-features-grid";
import { LandingWhySignalor } from "@/components/landing/landing-why-signalor";
import { LandingHero } from "@/components/landing/landing-hero";
import { LandingHowItWorks } from "@/components/landing/landing-how-it-works";
import { LandingTestimonials } from "@/components/landing/landing-testimonials";
import { LandingIntegrationsStrip } from "@/components/landing/landing-integrations-strip";
import { LandingPricingTeaser } from "@/components/landing/landing-pricing-teaser";
import { LandingFaq } from "@/components/landing/landing-faq";
import { LandingFooter } from "@/components/landing/landing-footer";
import { LandingMarketingShell } from "@/components/landing/landing-marketing-shell";
import { CornerDiamonds } from "@/components/ui/intersection-diamonds";
import { JsonLd } from "@/components/seo/json-ld";
import {
  breadcrumbJsonLd,
  buildMetadata,
  faqJsonLd,
  SITE_BRAND,
  SITE_URL,
} from "@/lib/seo";

const LLM_LOGOS = [
  { name: "ChatGPT", src: "/logos/chatgpt.svg" },
  { name: "Perplexity", src: "/logos/perplexity.svg" },
  { name: "Gemini", src: "/logos/gemini.svg" },
  { name: "Google AI", src: "/logos/google.svg" },
  { name: "Claude", src: "/logos/claude.svg" },
] as const;

const HOMEPAGE_FAQ = [
  {
    question: "What is Generative Engine Optimization (GEO)?",
    answer:
      "Generative Engine Optimization is the practice of preparing a website's content, structure, and trust signals so that AI engines like ChatGPT, Claude, Gemini, and Perplexity understand the page, treat it as authoritative, and cite it in their generated answers. Signalor scores GEO across six pillars: content, schema, E-E-A-T, technical, entity, and AI visibility.",
  },
  {
    question: "What is the difference between SEO and GEO?",
    answer:
      "Classic SEO targets the ten blue links of a search results page. GEO targets the answer text generated by an LLM — it requires answer-shaped content, complete Schema.org markup, strong entity signals, and verifiable trust markers so the model is willing to cite the source. Both still matter, but the optimization tactics differ.",
  },
  {
    question: "Which AI engines does Signalor track?",
    answer:
      "Signalor tracks brand presence and citations across ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), Perplexity, Google AI Overviews, and Microsoft Copilot. Engine coverage varies by plan — the Max plan includes all engines.",
  },
  {
    question: "How do I get started with Signalor?",
    answer:
      "Paste any public URL into the free analyzer at signalor.ai. You'll get a GEO score, citation signals, and a prioritized fix list — no install required. Create an account when you want to save runs and track changes over time.",
  },
  {
    question: "How does Signalor score a website?",
    answer:
      "Six weighted pillars: content (0.20), schema (0.15), E-E-A-T (0.20), technical (0.15), entity (0.15), and AI visibility (0.15). Each pillar rolls 5–15 sub-checks into a 0–100 score; the weighted average is the final GEO score, with prioritized fixes attached to each pillar.",
  },
  {
    question: "Does Signalor work with Shopify and WordPress?",
    answer:
      "Yes. Signalor offers a Shopify integration that scores product and content pages, and a self-hosted WordPress plugin (signalor-geo) that surfaces recommendations and applies one-click schema fixes inside the WordPress admin.",
  },
];

export const metadata: Metadata = buildMetadata({
  title: undefined,
  description:
    "Signalor scores, monitors, and improves how ChatGPT, Claude, Gemini, Perplexity, and Google AI cite your brand. Free GEO + AEO audit — paste any URL to start.",
  path: "/",
});

export default function Home() {
  const breadcrumbs = breadcrumbJsonLd([{ name: "Home", path: "/" }]);
  const faq = faqJsonLd(HOMEPAGE_FAQ);
  const product = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: SITE_BRAND,
    description:
      "GEO and AEO platform that scores how AI engines cite your brand and ships prioritized fixes.",
    brand: { "@type": "Brand", name: "Signalor" },
    url: SITE_URL,
    image: `${SITE_URL}/icon.svg`,
    offers: {
      "@type": "AggregateOffer",
      priceCurrency: "GBP",
      lowPrice: "19.99",
      highPrice: "59.99",
      offerCount: 3,
      url: `${SITE_URL}/pricing`,
    },
  };

  return (
    <LandingMarketingShell>
      <JsonLd id="ld-home-breadcrumb" data={breadcrumbs} />
      <JsonLd id="ld-home-faq" data={faq} />
      <JsonLd id="ld-home-product" data={product} />

      <LandingHero />

      <section
        className="relative  border-t border-border/60 bg-background/80 py-12 backdrop-blur-sm"
        aria-label="Supported AI engines"
      >
        <CornerDiamonds top />
        <div className=" mx-auto max-w-7xl px-6 lg:px-12">
          <p className="text-[11px] font-medium uppercase tracking-[0.22em] text-neutral-400">
            [ works with every major AI engine ]
          </p>
          <ul className="mt-6 flex flex-wrap items-center gap-x-12 gap-y-8 md:gap-x-16">
            {LLM_LOGOS.map(({ name, src }) => (
              <li
                key={name}
                className="group flex shrink-0 flex-col items-center gap-2"
                title={name}
              >
                <img
                  src={src}
                  alt={`${name} logo — supported by Signalor`}
                  width={160}
                  height={48}
                  decoding="async"
                  className="h-9 w-auto max-w-40 object-contain object-center transition duration-300 ease-out group-hover:scale-[1.04] md:h-10 md:max-w-44"
                />
                <span className="sr-only">{name}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <LandingHowItWorks />
      <LandingFeaturesGrid />
      <LandingTestimonials />
      <LandingWhySignalor />
      <LandingIntegrationsStrip />
      <LandingPricingTeaser />
      <LandingFaq items={HOMEPAGE_FAQ} />
      <LandingFooter />
    </LandingMarketingShell>
  );
}
