import type { TourStep } from "./tour";

export const ONBOARDING_STEPS: TourStep[] = [
  // ── Overview ──────────────────────────────────────────────────────────
  {
    kind: "modal",
    id: "welcome",
    section: "overview",
    title: "Welcome to Signalor",
    body: (
      <>
        A short tour of Overview — we&apos;ll walk through the cards on this page one at a time.
        When you visit other sections (Visibility, Sitemap, Tracker, etc.) you&apos;ll get a tour
        for those too.
      </>
    ),
    route: "",
  },
  {
    kind: "spotlight",
    id: "nav-overview",
    section: "overview",
    selector: '[data-tour="nav-overview"]',
    title: "Overview",
    body: "You're here. Overview is the page you'll open most — it's your daily snapshot.",
    side: "right",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-header",
    section: "overview",
    selector: '[data-tour-card="overview-header"]',
    title: "Run header & quick actions",
    body: "Project name, current run status, and three actions: Re-analyze (refresh now), Schedule analysis (recurring), and Export (PDF report).",
    side: "bottom",
    align: "start",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-score",
    section: "overview",
    selector: '[data-tour-card="overview-score"]',
    title: "GEO score",
    body: "Your composite score across all six pillars — content, schema, E-E-A-T, technical, entity, AI visibility. The arrow below shows movement since the last run.",
    side: "right",
    align: "start",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-performance",
    section: "overview",
    selector: '[data-tour-card="overview-performance"]',
    title: "Weekly performance",
    body: "How the GEO score has trended week over week. Use this to spot regressions early — a drop here usually points to a new content or technical issue.",
    side: "left",
    align: "start",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-platforms",
    section: "overview",
    selector: '[data-tour-card="overview-platforms"]',
    title: "Visibility by platform",
    body: "How visible your brand is on each AI surface — ChatGPT, Gemini, Perplexity, Claude, plus Google and Bing. Wide gaps between platforms tell you where to focus.",
    side: "right",
    align: "start",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-pillars",
    section: "overview",
    selector: '[data-tour-card="overview-pillars"]',
    title: "Pillar breakdown",
    body: "Per-pillar contribution to the overall score. The lowest bar is your biggest lift opportunity — that's usually where Tasks should send you next.",
    side: "left",
    align: "start",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-sentiment",
    section: "overview",
    selector: '[data-tour-card="overview-sentiment"]',
    title: "Sentiment analysis",
    body: "How AI-generated answers describe your brand — positive, negative, or neutral. Track this when you're managing reputation or running a brand campaign.",
    side: "left",
    align: "start",
    route: "",
  },
  {
    kind: "spotlight",
    id: "overview-reach",
    section: "overview",
    selector: '[data-tour-card="overview-reach"]',
    title: "Social brand reach",
    body: "Where your brand shows up across regions on social. Hover countries for the per-region breakdown.",
    side: "top",
    align: "start",
    route: "",
  },

  // ── Visibility ────────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-visibility",
    section: "visibility",
    selector: '[data-tour="nav-visibility"]',
    title: "Visibility",
    body: "How AI surfaces (ChatGPT, Perplexity, Gemini) currently see your brand.",
    side: "right",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-header",
    section: "visibility",
    selector: '[data-tour-card="visibility-header"]',
    title: "Connect Analytics",
    body: "Wire up GA4 here so we can correlate visibility with real traffic. The pill turns green once connected.",
    side: "bottom",
    align: "start",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-overall",
    section: "visibility",
    selector: '[data-tour-card="visibility-overall"]',
    title: "Overall visibility score",
    body: "The headline number — how AI engines and platforms surface your brand on average, from 0 to 100. Anything under 40 needs urgent attention; 70+ means you're well-cited.",
    side: "bottom",
    align: "start",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-kpi-google",
    section: "visibility",
    selector: '[data-tour-card="visibility-kpi-google"]',
    title: "Google score",
    body: "Your visibility on Google specifically — brand rank, indexing depth, SERP coverage. Most LLMs lean on Google's index, so weak signal here cascades to AI surfaces.",
    side: "bottom",
    align: "center",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-kpi-reddit",
    section: "visibility",
    selector: '[data-tour-card="visibility-kpi-reddit"]',
    title: "Reddit score",
    body: "Your presence in Reddit threads about your category. Reddit is heavily represented in LLM training data — a high Reddit score often correlates with strong AI mentions.",
    side: "bottom",
    align: "center",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-kpi-web",
    section: "visibility",
    selector: '[data-tour-card="visibility-kpi-web"]',
    title: "Web score",
    body: "Mentions across the open web — blogs, news, forums, review sites. The broader the citation footprint, the more confidently LLMs cite you back.",
    side: "bottom",
    align: "center",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-kpi-coverage",
    section: "visibility",
    selector: '[data-tour-card="visibility-kpi-coverage"]',
    title: "Coverage",
    body: "What share of the platforms we check actually surface your brand at all. 100% coverage means you appear everywhere we look, even if scores vary.",
    side: "bottom",
    align: "end",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-insights",
    section: "visibility",
    selector: '[data-tour-card="visibility-insights"]',
    title: "AI engine & platform signals",
    body: "Share of voice across AI engines (left bar chart), the mentions-by-engine donut (middle), and platform coverage (right). This is where you spot which engines are missing your brand entirely.",
    side: "bottom",
    align: "start",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-google",
    section: "visibility",
    selector: '[data-tour-card="visibility-google"]',
    title: "Google deep dive",
    body: "Brand rank, indexed pages, SERP coverage, plus Knowledge Panel and AI Overview presence. The breakdown bars show which signals are driving (or dragging) your Google score.",
    side: "right",
    align: "start",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-reddit",
    section: "visibility",
    selector: '[data-tour-card="visibility-reddit"]',
    title: "Reddit deep dive",
    body: "Mentions, upvotes, comment volume, and sentiment from Reddit threads about your brand. Reddit weighs heavily in modern LLM training data, so weak signal here often correlates with poor AI visibility.",
    side: "right",
    align: "start",
    route: "/visibility",
  },
  {
    kind: "spotlight",
    id: "visibility-web",
    section: "visibility",
    selector: '[data-tour-card="visibility-web"]',
    title: "Web mentions",
    body: "Total mentions across the open web with breakdown by source type — blogs, news, forums, social, reviews. The Top links list shows individual citations you can verify or build on.",
    side: "left",
    align: "start",
    route: "/visibility",
  },

  // ── Sitemap ───────────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-sitemap",
    section: "sitemap",
    selector: '[data-tour="nav-sitemap"]',
    title: "Sitemap",
    body: "Page-level audit — speed, structured data, and AI readiness for every URL we crawled.",
    side: "right",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-tabs",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-tabs"]',
    title: "Sitemap & Agent log",
    body: "Two views — Sitemap (the per-page audit) and Agent log (live activity feed, coming soon). For now, you'll mostly live on the Sitemap tab.",
    side: "bottom",
    align: "start",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-header",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-header"]',
    title: "Sitemap source & re-run",
    body: "Shows which sitemap URL we're crawling. Click Re-run audit to refresh the data — useful after you've shipped fixes and want to verify them.",
    side: "bottom",
    align: "start",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-stat-indexed",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-stat-indexed"]',
    title: "Indexed pages",
    body: "How many URLs we've successfully crawled out of your sitemap. The bar shows progress toward your crawl limit (200 URLs per run).",
    side: "bottom",
    align: "start",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-stat-lcp",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-stat-lcp"]',
    title: "Avg LCP",
    body: "Largest Contentful Paint — how fast your main content loads. Under 2.5s is good (green), under 4s warns, beyond is failing.",
    side: "bottom",
    align: "center",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-stat-fcp",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-stat-fcp"]',
    title: "Avg FCP",
    body: "First Contentful Paint — when the user sees the first pixel of meaningful content. Under 1.8s is good, under 3s warns.",
    side: "bottom",
    align: "center",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-stat-ttfb",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-stat-ttfb"]',
    title: "Avg TTFB",
    body: "Time to First Byte — how fast your server responds. Under 800ms is good. High TTFB usually points to backend or hosting issues.",
    side: "bottom",
    align: "end",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-state-tabs",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-state-tabs"]',
    title: "Filter by crawl state",
    body: "Switch between Crawled, Redirects, Queued, and Failed pages. Failed is the most urgent bucket — those URLs aren't indexable so they earn nothing.",
    side: "bottom",
    align: "start",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-toolbar",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-toolbar"]',
    title: "Search, filter, sort",
    body: "Search URLs, filter by severity (OK / Warning / Fail), and sort by score, vitals, or path. Severity = Fail is what you want to attack first.",
    side: "bottom",
    align: "end",
    route: "/sitemap",
  },
  {
    kind: "spotlight",
    id: "sitemap-row",
    section: "sitemap",
    selector: '[data-tour-card="sitemap-row"]',
    title: "A page row",
    body: "Each row is one URL. You'll see status, content depth, Core Web Vitals (LCP/FCP/TTFB), server time, resources, link counts, and an AI-readiness score. Click any row to expand and see exactly which checks passed or failed.",
    side: "bottom",
    align: "start",
    route: "/sitemap",
  },

  // ── Tasks ─────────────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-tasks",
    section: "tasks",
    selector: '[data-tour="nav-tasks"]',
    title: "Tasks",
    body: "Prioritised fixes ranked by expected lift — start at the top.",
    side: "right",
    route: "/recommendations",
  },
  {
    kind: "spotlight",
    id: "tasks-toolbar",
    section: "tasks",
    selector: '[data-tour-card="tasks-toolbar"]',
    title: "Filter the list",
    body: "Narrow tasks by pillar, priority, or status. Useful when you want to batch quick wins or focus on a single area like schema.",
    side: "bottom",
    align: "start",
    route: "/recommendations",
  },
  {
    kind: "spotlight",
    id: "tasks-row",
    section: "tasks",
    selector: '[data-tour-card="tasks-row"]',
    title: "A recommendation",
    body: "Each row is one fix, ranked by impact. The XP and time estimate help you batch quick wins. Click to expand for the full description, steps, and an Auto Fix or Manual action.",
    side: "bottom",
    align: "start",
    route: "/recommendations",
  },

  // ── Tracker ───────────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-tracker",
    section: "tracker",
    selector: '[data-tour="nav-tracker"]',
    title: "Tracker",
    body: "Watch real LLM responses for prompts that matter to your category.",
    side: "right",
    route: "/prompts",
  },
  {
    kind: "spotlight",
    id: "tracker-toolbar",
    section: "tracker",
    selector: '[data-tour-card="tracker-toolbar"]',
    title: "Tracker toolbar",
    body: "Add a prompt with New prompt, search across what you've added, filter by strength, sort, or hit Recheck all to re-run every prompt across every engine.",
    side: "bottom",
    align: "start",
    route: "/prompts",
  },
  {
    kind: "spotlight",
    id: "tracker-stats",
    section: "tracker",
    selector: '[data-tour-card="tracker-stats"]',
    title: "Tracker stats",
    body: "At-a-glance health of your tracked prompts — average score, visibility percentage, count of strong prompts, and total runs. The first two move when you add prompts or fix issues; watch them weekly.",
    side: "bottom",
    align: "start",
    route: "/prompts",
  },
  {
    kind: "spotlight",
    id: "tracker-row",
    section: "tracker",
    selector: '[data-tour-card="tracker-row"]',
    title: "A tracked prompt",
    body: "Each card is one prompt you're watching. The score on the left shows current visibility; click to expand and see the actual responses from ChatGPT, Gemini, Perplexity, etc. — including whether your brand was cited.",
    side: "bottom",
    align: "start",
    route: "/prompts",
  },

  // ── Competitors ───────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-competitors",
    section: "competitors",
    selector: '[data-tour="nav-competitors"]',
    title: "Competitors",
    body: "Benchmark rivals across the same AI surfaces you're tracked on.",
    side: "right",
    route: "/competitors",
  },
  {
    kind: "spotlight",
    id: "competitors-toolbar",
    section: "competitors",
    selector: '[data-tour-card="competitors-toolbar"]',
    title: "Manage competitors",
    body: "Filter by confidence or score band, and use the + button to add a competitor manually if our auto-discovery missed one.",
    side: "bottom",
    align: "start",
    route: "/competitors",
  },
  {
    kind: "spotlight",
    id: "competitors-table",
    section: "competitors",
    selector: '[data-tour-card="competitors-table"]',
    title: "Competitor table",
    body: "All competitors with their composite score next to yours. Sort by score to find who's pulling ahead and click into a competitor to see their full breakdown.",
    side: "top",
    align: "start",
    route: "/competitors",
  },

  // ── Content ───────────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-content",
    section: "content",
    selector: '[data-tour="nav-content"]',
    title: "Content",
    body: "An in-app editor for AI-optimised pages. Each piece is scored against the same six pillars before publish.",
    side: "right",
    route: "/optimisation/content",
  },
  {
    kind: "spotlight",
    id: "content-chrome",
    section: "content",
    selector: '[data-tour-card="content-chrome"]',
    title: "Page picker & address bar",
    body: "Pick which page on your site to edit. Back, forward, and refresh work like a browser; the URL field lets you jump to any page directly.",
    side: "bottom",
    align: "start",
    route: "/optimisation/content",
  },
  {
    kind: "spotlight",
    id: "content-iframe",
    section: "content",
    selector: '[data-tour-card="content-iframe"]',
    title: "Live preview",
    body: "Click any element in the preview — heading, paragraph, image — to select it. Selected elements open in the editor on the right where you can rewrite or apply changes.",
    side: "left",
    align: "start",
    route: "/optimisation/content",
  },

  // ── Backlinks ─────────────────────────────────────────────────────────
  {
    kind: "spotlight",
    id: "nav-backlinks",
    section: "backlinks",
    selector: '[data-tour="nav-backlinks"]',
    title: "Backlinks",
    body: "Earn citations on the open web — LLMs index these pages and weight them heavily.",
    side: "right",
    route: "/backlinks",
  },
  {
    kind: "spotlight",
    id: "backlinks-tabs",
    section: "backlinks",
    selector: '[data-tour-card="backlinks-tabs"]',
    title: "Free vs Paid",
    body: "Free shows submission targets you can act on yourself. Paid lists vetted placement marketplaces — we handle the order, you approve the placement.",
    side: "bottom",
    align: "start",
    route: "/backlinks",
  },
  {
    kind: "spotlight",
    id: "backlinks-free-row",
    section: "backlinks",
    selector: '[data-tour-card="backlinks-free-row"]',
    title: "A backlink opportunity",
    body: "Each row is one site where you could earn a backlink. The category tag (Directory, Review, Press, Community, Resource) and priority badge help you sequence outreach. Click the name to open the submission page in a new tab.",
    side: "bottom",
    align: "start",
    route: "/backlinks",
  },
];
